### ISSUE TITLE
Help on how to get started

### ISSUE THREAD

**Issue by gernest** [OADA/oada-docs#14]
Hello, this is a nice work. I am interested in implementing OADA clients and porivders in [Go Programming Language](http://golang.org/).

I am from Tanzania. And I like to do something that will help my people fight against poverty. I already an [OAuth 2,0](https://github.com/gernest/hero)  servie implemetation so I won't need to start from scratch.

My Question is, How do I get started? I mean the docs here are sparse and I couldn't grab anything that made it viable to deduct the path to take.

Thank you for  the great work that you are doing.

**Comment by aultac** [comment]
@gernest: great to hear from you!  Sorry for taking so long to reply: Thursday to Sunday this week is a holiday (Thanksgiving) in the US and I've been traveling with my family to visit relatives.  

We've had on our todo list for awhile that we need a better intro/tl;dr approach to the API to make it simpler to ease in to the project.  In the meantime, I think the best thing we could do is get a Gitter or Slack channel setup in order to chat live and see how we can help the best.  I'll work on that this weekend and see if we can coordinate some times to be online: are you on the EAT time zone?

We've had some other interest in a Go implementation, so I'll see if I can get you guys connected up to share resources.

Thanks!
Aaron

**Comment by gernest** [comment]
@aultac Nice to hear from you too. 

Not so sure that I will be online, but I will be following this Issue closerly so whenever I am online I will be checking here. Yes I'm in EAT timezone.

That will be great, I will be more than happy to help with the Go(Golang) implementations.

**Comment by aultac** [comment]
@gernest: Gitter badge is up on oada-docs Readme at the top: click it to chat via gitter.  If you're up for it, I'd like to get an idea of what areas are docs are weak at the moment in the hopes we can craft a better "getting started" message.  Thanks!!

**Comment by gernest** [comment]
@aultac great. Just joined the room.

**Comment by gernest** [comment]
Discussion moved to gitter
